# Generated by Django 3.1.7 on 2021-05-06 22:02

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='F_Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_kind', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('countries', django_countries.fields.CountryField(blank=True, max_length=746, multiple=True)),
                ('food_kinds', models.ManyToManyField(to='checklist.F_Kind')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
