# Generated by Django 3.1.7 on 2021-05-06 22:04

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_f_kind_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_kind', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('alcohol', models.BooleanField(default=False)),
                ('countries', django_countries.fields.CountryField(blank=True, max_length=746, multiple=True)),
                ('drink_kinds', models.ManyToManyField(to='checklist.D_kind')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
