# Generated by Django 3.1.7 on 2021-05-10 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_auto_20210507_0223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['order'], 'verbose_name': 'Food', 'verbose_name_plural': 'Food'},
        ),
    ]
