# Generated by Django 3.1.7 on 2021-05-21 11:08

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_auto_20210520_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
