# Generated by Django 3.1.7 on 2021-05-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_auto_20210521_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['ingredient'],
            },
        ),
    ]
