# Generated by Django 3.1.7 on 2021-05-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0012_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='drink_ingredients',
            field=models.ManyToManyField(blank=True, to='checklist.Ingredient'),
        ),
        migrations.AddField(
            model_name='food',
            name='food_ingredients',
            field=models.ManyToManyField(blank=True, to='checklist.Ingredient'),
        ),
    ]
