# Generated by Django 3.1.7 on 2021-06-02 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0013_auto_20210523_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_books', models.PositiveIntegerField(default=0)),
                ('num_movies', models.PositiveIntegerField(default=0)),
                ('num_food', models.PositiveIntegerField(default=0)),
                ('num_drinks', models.PositiveIntegerField(default=0)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
