# Generated by Django 3.1.7 on 2021-06-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0014_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='user_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
